"""GEOID VV normalization constants generated by compute_geoid_stats.

Run ``python -m water_seg.compute_geoid_stats --geoid-root PATH`` once before
pretraining. The scanner replaces ``None`` with constants and provenance for
the selected GEOID release.
"""


GEOID_VV_STATS = None
